{"original_position": 47, "diff_hunk": "@@ -52,3 +55,22 @@ def test_it_filters_by_locale(self, client):\n \n         recipe_names = set(r['name'] for r in res.data['recipes'])\n         assert recipe_names == {'german', 'any', 'both'}\n+\n+    @pytest.mark.xfail\n+    def test_it_makes_no_db_queries(self, client, django_cache):\n+        # Prepare some interesting data\n+        recipe_action = RecipeActionFactory(recipe__enabled=True)\n+        recipe = recipe_action.recipe\n+\n+        # Warm up the cache\n+        res1 = client.post('/api/v1/fetch_bundle/', {'locale': 'de'})\n+        assert res1.status_code == 200\n+        assert res1.data['recipes'][0]['name'] == recipe.name\n+\n+        # Fire!\n+        queries = CaptureQueriesContext(connection)\n+        with queries:\n+            res2 = client.post('/api/v1/fetch_bundle/', {'locale': 'de'})\n+            assert res2.status_code == 200\n+        assert res1.data == res2.data\n+        assert (len(queries), list(queries)) == (0, [])", "body_text": "Oh, this was mostly for debugging. Doing it this way showed me both a counter of how many tests were remaining, and also what the problematic queries were. I think this should just be comparing to the empty list (which gives really useful debugging when the test fails).", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/73", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/56375380", "created_at": "2016-03-16T17:16:10Z", "author_association": "MEMBER", "body": "Oh, this was mostly for debugging. Doing it this way showed me both a counter of how many tests were remaining, and also what the problematic queries were. I think this should just be comparing to the empty list (which gives really useful debugging when the test fails).\n", "updated_at": "2016-03-17T00:11:27Z", "html_url": "https://github.com/mozilla/normandy/pull/73#discussion_r56375380", "pull_request_review_id": null, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/56375380"}, "html": {"href": "https://github.com/mozilla/normandy/pull/73#discussion_r56375380"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/73"}}, "commit_id": "e13a6eb017def1dc9edce661cbda68c6f6b45199", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "position": null, "path": "normandy/classifier/tests/test_api.py", "body_html": "<p>Oh, this was mostly for debugging. Doing it this way showed me both a counter of how many tests were remaining, and also what the problematic queries were. I think this should just be comparing to the empty list (which gives really useful debugging when the test fails).</p>", "original_commit_id": "424fd9fd3dbf581789ebd382ef245eae5b147e64", "id": 56375380}