{"body": "There is silly test failure here, and a lint failure (there is a line in the migration that is too long). Besides that, it looks fine to me.\n\nr+ after CI passes.\n", "body_text": "There is silly test failure here, and a lint failure (there is a line in the migration that is too long). Besides that, it looks fine to me.\nr+ after CI passes.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/224959648", "created_at": "2016-06-09T17:00:58Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/157#issuecomment-224959648", "updated_at": "2016-06-09T17:00:58Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>There is silly test failure here, and a lint failure (there is a line in the migration that is too long). Besides that, it looks fine to me.</p>\n<p>r+ after CI passes.</p>", "id": 224959648, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/157"}