{"body": "The taskcluster failure had the line `virtual memory exhausted: Cannot allocate memory`, but it passed on the \"push\" build. I suspect this is a one-off thing that will work fine next time.", "body_text": "The taskcluster failure had the line virtual memory exhausted: Cannot allocate memory, but it passed on the \"push\" build. I suspect this is a one-off thing that will work fine next time.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/290139765", "created_at": "2017-03-29T16:09:32Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/613#issuecomment-290139765", "updated_at": "2017-03-29T16:09:32Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>The taskcluster failure had the line <code>virtual memory exhausted: Cannot allocate memory</code>, but it passed on the \"push\" build. I suspect this is a one-off thing that will work fine next time.</p>", "id": 290139765, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/613"}