{"body": "TC failure is #1110. The rest of this looks good.", "body_text": "TC failure is #1110. The rest of this looks good.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/337066486", "created_at": "2017-10-16T22:50:18Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/1104#issuecomment-337066486", "updated_at": "2017-10-16T22:50:18Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>TC failure is <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"265938315\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/mozilla/normandy/issues/1110\" href=\"https://github.com/mozilla/normandy/pull/1110\">#1110</a>. The rest of this looks good.</p>", "id": 337066486, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/1104"}