{"original_position": 4, "diff_hunk": "@@ -283,6 +283,12 @@ def test_recipe_update_locales(self):\n         recipe.update(locales=[])\n         assert recipe.locales.count() == 0\n \n+    def test_recipe_update_arguments(self):", "body_text": "Can you also add an API test that reproduces the error POSTing to the view? That'd be closer to the situation we're actually seeing the error in.", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/463", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/98788989", "created_at": "2017-01-31T22:38:50Z", "author_association": "MEMBER", "body": "Can you also add an API test that reproduces the error POSTing to the view? That'd be closer to the situation we're actually seeing the error in.", "updated_at": "2017-01-31T22:59:41Z", "html_url": "https://github.com/mozilla/normandy/pull/463#discussion_r98788989", "pull_request_review_id": 19442725, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/98788989"}, "html": {"href": "https://github.com/mozilla/normandy/pull/463#discussion_r98788989"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/463"}}, "commit_id": "e0d8d6b5b237fd736ba3c688b5d814cf251bd5ea", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "position": 4, "path": "recipe-server/normandy/recipes/tests/test_models.py", "body_html": "<p>Can you also add an API test that reproduces the error POSTing to the view? That'd be closer to the situation we're actually seeing the error in.</p>", "original_commit_id": "f1839d61eb2acec295a011c48952251646d1e52d", "id": 98788989}