{"body": "> I'm having trouble getting the test(s) for this feature to work. It doesn't seem to catch errors as it should, and manually throwing hard errors in start doesn't bubble up to the test runner, either. I'm wondering if I have the yield syntax incorrect or something.\r\n\r\nI ran into this too, and Osmose and I tracked it down: it turns out that one of our `with...` helper methods doesn't work with generators, and only works with async/await functions. Converting the test to async/await made them work for me. It was as simple as replace `yield` with `await` and `function*` with `async function`.", "body_text": "I'm having trouble getting the test(s) for this feature to work. It doesn't seem to catch errors as it should, and manually throwing hard errors in start doesn't bubble up to the test runner, either. I'm wondering if I have the yield syntax incorrect or something.\n\nI ran into this too, and Osmose and I tracked it down: it turns out that one of our with... helper methods doesn't work with generators, and only works with async/await functions. Converting the test to async/await made them work for me. It was as simple as replace yield with await and function* with async function.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/293406951", "created_at": "2017-04-11T21:34:07Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/673#issuecomment-293406951", "updated_at": "2017-04-11T21:34:07Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<blockquote>\n<p>I'm having trouble getting the test(s) for this feature to work. It doesn't seem to catch errors as it should, and manually throwing hard errors in start doesn't bubble up to the test runner, either. I'm wondering if I have the yield syntax incorrect or something.</p>\n</blockquote>\n<p>I ran into this too, and Osmose and I tracked it down: it turns out that one of our <code>with...</code> helper methods doesn't work with generators, and only works with async/await functions. Converting the test to async/await made them work for me. It was as simple as replace <code>yield</code> with <code>await</code> and <code>function*</code> with <code>async function</code>.</p>", "id": 293406951, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/673"}