{"body": "> I'm afraid I don't understand what problem this is trying to solve. Can you clarify what steps currently show an issue here?\r\n\r\nHere's two add-ons:\r\n\r\n- https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-foo.xpi\r\n- https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-bar.xpi\r\n\r\nBoth have a function `RecipeRunner.example()` that logs an error message to the console; one logs `\"FOO\"`, the other logs `\"BAR\"`.\r\n\r\nInstall one of them, then restart the browser to get a fresh state. Run this in the browser console:\r\n\r\n```js\r\nCu.import(\"resource://shield-recipe-client/lib/RecipeRunner.jsm\");\r\nRecipeRunner.example();\r\n```\r\n\r\nIt should log the error message for the version you installed. Now, install the other XPI without restarting. In theory, `Cu.unload` gets called during shutdown, and so if you run the lines above again after the update, it should log a different message. In practice, for some reason, it logs the same message even though the code updated. If you restart Firefox, then re-run the code above, it logs the correct message.\r\n\r\nUnloading from within the Browser Console fixes the issue, at least within the Browser Console.\r\n\r\n> Are we sure that that uninstall code is running?\r\n\r\nYeah, I tested this by logging an error message from the `shutdown` method, and it logged successfully when upgrading the add-on.", "body_text": "I'm afraid I don't understand what problem this is trying to solve. Can you clarify what steps currently show an issue here?\n\nHere's two add-ons:\n\nhttps://dl.dropboxusercontent.com/u/168762/shield-recipe-client-foo.xpi\nhttps://dl.dropboxusercontent.com/u/168762/shield-recipe-client-bar.xpi\n\nBoth have a function RecipeRunner.example() that logs an error message to the console; one logs \"FOO\", the other logs \"BAR\".\nInstall one of them, then restart the browser to get a fresh state. Run this in the browser console:\nCu.import(\"resource://shield-recipe-client/lib/RecipeRunner.jsm\");\nRecipeRunner.example();\nIt should log the error message for the version you installed. Now, install the other XPI without restarting. In theory, Cu.unload gets called during shutdown, and so if you run the lines above again after the update, it should log a different message. In practice, for some reason, it logs the same message even though the code updated. If you restart Firefox, then re-run the code above, it logs the correct message.\nUnloading from within the Browser Console fixes the issue, at least within the Browser Console.\n\nAre we sure that that uninstall code is running?\n\nYeah, I tested this by logging an error message from the shutdown method, and it logged successfully when upgrading the add-on.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/284879715", "created_at": "2017-03-07T22:23:03Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/578#issuecomment-284879715", "updated_at": "2017-03-07T22:23:26Z", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "body_html": "<blockquote>\n<p>I'm afraid I don't understand what problem this is trying to solve. Can you clarify what steps currently show an issue here?</p>\n</blockquote>\n<p>Here's two add-ons:</p>\n<ul>\n<li><a href=\"https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-foo.xpi\" rel=\"nofollow\">https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-foo.xpi</a></li>\n<li><a href=\"https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-bar.xpi\" rel=\"nofollow\">https://dl.dropboxusercontent.com/u/168762/shield-recipe-client-bar.xpi</a></li>\n</ul>\n<p>Both have a function <code>RecipeRunner.example()</code> that logs an error message to the console; one logs <code>\"FOO\"</code>, the other logs <code>\"BAR\"</code>.</p>\n<p>Install one of them, then restart the browser to get a fresh state. Run this in the browser console:</p>\n<div class=\"highlight highlight-source-js\"><pre><span class=\"pl-smi\">Cu</span>.<span class=\"pl-en\">import</span>(<span class=\"pl-s\"><span class=\"pl-pds\">\"</span>resource://shield-recipe-client/lib/RecipeRunner.jsm<span class=\"pl-pds\">\"</span></span>);\n<span class=\"pl-smi\">RecipeRunner</span>.<span class=\"pl-en\">example</span>();</pre></div>\n<p>It should log the error message for the version you installed. Now, install the other XPI without restarting. In theory, <code>Cu.unload</code> gets called during shutdown, and so if you run the lines above again after the update, it should log a different message. In practice, for some reason, it logs the same message even though the code updated. If you restart Firefox, then re-run the code above, it logs the correct message.</p>\n<p>Unloading from within the Browser Console fixes the issue, at least within the Browser Console.</p>\n<blockquote>\n<p>Are we sure that that uninstall code is running?</p>\n</blockquote>\n<p>Yeah, I tested this by logging an error message from the <code>shutdown</code> method, and it logged successfully when upgrading the add-on.</p>", "id": 284879715, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/578"}