{"body": "I'm not sure what's going on with that test. @Osmose, @rehandalal, do either of you have any ideas? I can't get the failure to happen locally.\n", "body_text": "I'm not sure what's going on with that test. @Osmose, @rehandalal, do either of you have any ideas? I can't get the failure to happen locally.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/250245313", "created_at": "2016-09-28T17:54:30Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/276#issuecomment-250245313", "updated_at": "2016-09-28T17:54:30Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>I'm not sure what's going on with that test. <a class=\"user-mention\" href=\"https://github.com/osmose\">@Osmose</a>, <a class=\"user-mention\" href=\"https://github.com/rehandalal\">@rehandalal</a>, do either of you have any ideas? I can't get the failure to happen locally.</p>", "id": 250245313, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/276"}