{"body": "What error? We don't actually use the LogManager in that block.", "body_text": "What error? We don't actually use the LogManager in that block.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/276126890", "created_at": "2017-01-30T17:23:17Z", "author_association": "CONTRIBUTOR", "html_url": "https://github.com/mozilla/normandy/pull/458#issuecomment-276126890", "updated_at": "2017-01-30T17:23:17Z", "user": {"following_url": "https://api.github.com/users/gijsk/following{/other_user}", "events_url": "https://api.github.com/users/gijsk/events{/privacy}", "organizations_url": "https://api.github.com/users/gijsk/orgs", "url": "https://api.github.com/users/gijsk", "gists_url": "https://api.github.com/users/gijsk/gists{/gist_id}", "html_url": "https://github.com/gijsk", "subscriptions_url": "https://api.github.com/users/gijsk/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/375983?v=4", "repos_url": "https://api.github.com/users/gijsk/repos", "received_events_url": "https://api.github.com/users/gijsk/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/gijsk/starred{/owner}{/repo}", "site_admin": false, "login": "gijsk", "type": "User", "id": 375983, "followers_url": "https://api.github.com/users/gijsk/followers"}, "body_html": "<p>What error? We don't actually use the LogManager in that block.</p>", "id": 276126890, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/458"}