{"body": "What's even more wow was that I tested curl'ing `/api/v1/recipe/` locally and didn't encounter this error. I'll look into it tomorrow. Perhaps I curl'ed before actually pip installing. Or perhaps I didn't notice the error or something. ", "body_text": "What's even more wow was that I tested curl'ing /api/v1/recipe/ locally and didn't encounter this error. I'll look into it tomorrow. Perhaps I curl'ed before actually pip installing. Or perhaps I didn't notice the error or something.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/371327212", "created_at": "2018-03-07T23:50:58Z", "author_association": "CONTRIBUTOR", "html_url": "https://github.com/mozilla/normandy/pull/1204#issuecomment-371327212", "updated_at": "2018-03-07T23:50:58Z", "user": {"following_url": "https://api.github.com/users/peterbe/following{/other_user}", "events_url": "https://api.github.com/users/peterbe/events{/privacy}", "organizations_url": "https://api.github.com/users/peterbe/orgs", "url": "https://api.github.com/users/peterbe", "gists_url": "https://api.github.com/users/peterbe/gists{/gist_id}", "html_url": "https://github.com/peterbe", "subscriptions_url": "https://api.github.com/users/peterbe/subscriptions", "avatar_url": "https://avatars2.githubusercontent.com/u/26739?v=4", "repos_url": "https://api.github.com/users/peterbe/repos", "received_events_url": "https://api.github.com/users/peterbe/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/peterbe/starred{/owner}{/repo}", "site_admin": false, "login": "peterbe", "type": "User", "id": 26739, "followers_url": "https://api.github.com/users/peterbe/followers"}, "body_html": "<p>What's even more wow was that I tested curl'ing <code>/api/v1/recipe/</code> locally and didn't encounter this error. I'll look into it tomorrow. Perhaps I curl'ed before actually pip installing. Or perhaps I didn't notice the error or something.</p>", "id": 371327212, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/1204"}